# Generated by Django 5.1.2 on 2024-11-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=250, unique=True, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "fullname",
                    models.CharField(max_length=250, verbose_name="Full name"),
                ),
                ("comment", models.TextField(verbose_name="Comment")),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attempt_datetime", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Успешно"), ("failed", "Неуспешно")],
                        max_length=10,
                    ),
                ),
                ("server_response", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Mailing attempt",
                "verbose_name_plural": "Mailing attempts",
                "ordering": ["-attempt_datetime"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_message", models.TextField(verbose_name="text_subject")),
                ("body_message", models.TextField(verbose_name="text_message")),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date created"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("started", "Started"),
                            ("finished", "Finished"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletters.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mailing",
                "verbose_name_plural": "Mailings",
                "ordering": ["-date_created"],
            },
        ),
    ]
