# Generated by Django 5.1.2 on 2024-11-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                related_name="clients", to="newsletters.client"
            ),
        ),
    ]
